### ISSUE TITLE
Upgrade Chronos 3.x

### ISSUE THREAD

**Issue by stissot** [Ecodev/felix#21]
Now that PHP 8.2 is required by Felix, we should upgrade to Chronos to 3.x, to leaverage support of `ChronosTime` to represent times without a date

**Comment by PowerKiKi** [comment]
I think it was the fact that Chronos does not implement native interfaces, meaning they become incompatible with all other libs, eg: dbal, phpspreadsheet, etc.

**Comment by PowerKiKi** [comment]
See https://github.com/cakephp/chronos/issues/377. This would be quite a big thing to migrate all our code of all our project to that. We definitely should do it sometime, but I'm not sure now is the right time
